apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-vm
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora-vm
    spec:
      domain:
        cpu:
          cores: 1
        memory:
          guest: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: fedora-vm-disk
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: sourav
              password: redhat123
              chpasswd:
                expire: false
  dataVolumeTemplates:
    - metadata:
        name: fedora-vm-disk
      spec:
        source:
          pvc:
            namespace: openshift-virtualization-os-images
            name: fedora
        storage:
          resources:
            requests:
              storage: 35Gi
